### ISSUE TITLE
Domain adaptation

### ISSUE THREAD

**Issue by kimkj38** [jamycheung/Trans4PASS#10]
Thanks for your great work and I have questions about domain adaptation code.
Top 3 commands in the picture is for Trans4PASS and the last command is for Trans4PASS+? I checked that MPA+SSL+MS showed the best performance on your paper. Which command do I need to run for this method?

![image](https://github.com/jamycheung/Trans4PASS/assets/76815825/cbd92887-c801-4ae4-8d44-33a46ee84788)

**Comment by jamycheung** [comment]
Hi, yes, the top 3 commands are needed for that result of Trans4PASS. For Trans4PASS+, you would need to load the corresponding model. Both you could find [here](https://github.com/jamycheung/Trans4PASS/tree/main/adaptations/model).
