### ISSUE TITLE
Question about the MPA+SSL

### ISSUE THREAD

**Issue by ywher** [jamycheung/Trans4PASS#11]
Hi, nice work! I am trying to reproduce your experiments about domain adaptation.
I find the train_ssl.py and train_mpa.py in the adaptation folder.
For the results in Figure 4 (b), is train_ssl.py for SSL results, and train_mpa.py for MPA results? Or does train_mpa.py correspond to MPA+SSL results? If not, how can the best MPA+SSL results be reproduced?

**Comment by jamycheung** [comment]
Hi, thanks for your interest. 
For the results in Figure 4 (b), is train_ssl.py for SSL results, and train_mpa.py for MPA results? 

- In Table 4 (b), the SSL results is from the `train_ssl.py`. The `train_mpa.py` is to perform MPA after the `train_ssl.py` for SSL step. 

how can the best MPA+SSL results be reproduced?

- The best MPA+SSL can be obtained by `train_warm.py`, `train_ssl.py` and `train_mpa.py`.

Hope this help :)
