### ISSUE TITLE
How to draw Figure 5 ?

### ISSUE THREAD

**Issue by yanzq95** [jamycheung/Trans4PASS#3]
Hello, 
Figure 5 illustrates very clearly the advantage of handling distortion. Would you like to share an example about how to draw it （Yanzq@njust.edu.cn） ？thks~

**Comment by jamycheung** [comment]
Hi,
thanks for your interest. To plot Figure 5, the panoramic image is divided into 8 directions and evaluated individually. The tool to plot the figure can be matplotlib or something else.
