### ISSUE TITLE
RANDOMPERSPECTIVE

### ISSUE THREAD

**Issue by brucetend** [jamycheung/Trans4PASS#6]
There seems to be a problem with Randomperspective, which will make gt and input misaligned.
![image](https://user-images.githubusercontent.com/49537684/217945076-4a9126ee-6f00-444e-8adb-513a472e5b42.png)

**Comment by jamycheung** [comment]
Hi,
Thanks for your interest. This augmentation is borrowed from this [repository](https://github.com/LikeLy-Journey/SegmenTron), but it is not applied in our training. But really thanks for pointing out this.

Best
