### ISSUE TITLE
simplified version

### ISSUE THREAD

**Issue by W-Kinlon** [jamycheung/Trans4PASS#9]
Hi, I want to use Trans4PASS to train my own dataset and obtain my own set of metrics. Could you provide a simplified version of the network that only requires input of size and segmentation type?

**Comment by jamycheung** [comment]
Hi, thanks for your interest.

If you want to train on your onw dataset, one possible solution is to modify one of the dataloaders (check [here](https://github.com/jamycheung/Trans4PASS/tree/main/segmentron/data/dataloader)). About the metric, it would be helpful to check [existing metrics](https://github.com/jamycheung/Trans4PASS/blob/main/segmentron/utils/score.py). 

If I understand correctly, you could create demo scripts regarding `eval_xx.py` files [here](https://github.com/jamycheung/Trans4PASS/tree/main/tools).
